version: '3'
services:
  api-gateway:
    build:
      context: ./apigateways
    ports:
      - "8080:8080"
#    depends_on:
#      - eureka-server
#      - customer-services
    networks:
      - mynetwork

  eureka-server:
    build:
      context: ./finaleureka
    ports:
      - "8761:8761"
    networks:
      - mynetwork
  mysql:
    image: mysql:latest
    ports:
      - "3301:3301"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: 12345
      MYSQL_USER: root
      MYSQL_PASSWORD: 12345
    networks:
      - mynetwork
  finaljwt:
    build:
      context: ./finaljwt
    ports:
      - "8081:8081"
    depends_on:
      - eureka-server
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3301/jwtDb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 12345
    networks:
      - mynetwork



networks:
  mynetwork:

